# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: beed9003c6491589d176666152ca39dcc8bdec42d762fa6b9488ea5464bd96d52ce5a24464ec6633689c17c135f3753a128aec426b591094decc8990c85ad217

test:
  secret_key_base: 2a7b7d896e9f7f19e9920ce286c680b4be9559ea4701c6eb80f2e29126e2f207b5091d26b5dbad4d9aab6c618afc4926496eda012ccf8369d7144523c296b252

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: beed9003c6491589d176666152ca39dcc8bdec42d762fa6b9488ea5464bd96d52ce5a24464ec6633689c17c135f3753a128aec426b591094decc8990c85ad217
